### ISSUE TITLE
error : cannot use 'throw' with exceptions disabled

### ISSUE THREAD

**Issue by alake1** [microsoft/BitNet#75]
I am on Windows 10. When I run  
python setup_env.py -md models/Llama3-8B-1.58-100B-tokens -q i2_s
I get
ERROR:root:Error occurred while running command: Command '['cmake', '--build', 'build', '--config', 'Release']' returned non-zero exit status 1., check details in logs\compile.log

In compile.log --

Building Custom Rule C:/Users/ut/Desktop/Danet/BitNet/3rdparty/llama.cpp/src/CMakeLists.txt
C:\Users\ut\Desktop\Danet\BitNet\3rdparty\llama.cpp\src\llama.cpp(122,9): error : cannot use 'throw' with exceptions disabled [C:\Users\ut\Desktop\Danet\BitNet\build\3rdparty\llama.cpp\src\llama.vcxproj]

**Comment by GTJoey** [comment]
upgrade clang >= 18.0 .
default clang version 17.0.3 in vs2022 will get this problem.

**Comment by Chandanpoddar26** [comment]
Still same issue after updating clang to 19.0 version
